Nov-14 09:39:30.657 [main] DEBUG nextflow.cli.Launcher - $> nextflow kuberun login -v pvc-8be4fba1-00d5-11ea-b80d-42010a8e0073
Nov-14 09:39:35.166 [main] DEBUG nextflow.k8s.K8sConfig - Kubernetes workDir=/workspace/cole/work; projectDir=/workspace/projects; volumeClaims=[pvc-8be4fba1-00d5-11ea-b80d-42010a8e0073]
Nov-14 09:39:36.581 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.k8s.client.K8sResponseException: Request GET /api/v1/namespaces/default/persistentvolumeclaims/pvc-8be4fba1-00d5-11ea-b80d-42010a8e0073 returned an error code=403

  {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {
          
      },
      "status": "Failure",
      "message": "persistentvolumeclaims \"pvc-8be4fba1-00d5-11ea-b80d-42010a8e0073\" is forbidden: User \"system:serviceaccount:default:default\" cannot get resource \"persistentvolumeclaims\" in API group \"\" in the namespace \"default\"",
      "reason": "Forbidden",
      "details": {
          "name": "pvc-8be4fba1-00d5-11ea-b80d-42010a8e0073",
          "kind": "persistentvolumeclaims"
      },
      "code": 403
  }

	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:369)
	at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy)
	at nextflow.k8s.client.K8sClient.get(K8sClient.groovy:378)
	at nextflow.k8s.client.K8sClient.volumeClaimRead(K8sClient.groovy:428)
	at nextflow.k8s.K8sConfig.checkStorageAndPaths(K8sConfig.groovy:215)
	at nextflow.k8s.K8sConfig$checkStorageAndPaths$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at nextflow.k8s.K8sDriverLauncher.run(K8sDriverLauncher.groovy:122)
	at nextflow.cli.CmdKubeRun.run(CmdKubeRun.groovy:74)
	at nextflow.cli.Launcher.run(Launcher.groovy:451)
	at nextflow.cli.Launcher.main(Launcher.groovy:633)
